export const CALIDAD_START_ACTION = 'CALIDAD_START_ACTION';
export const CALIDAD_STOP_ACTION = 'CALIDAD_STOP_ACTION';
export const CALIDAD_AGREGAR_NUMERO = 'CALIDAD_AGREGAR_NUMERO';
export const CALIDAD_GUARDA_ESTADO = 'CALIDAD_GUARDA_ESTADO';
export const CALIDAD_SOLICITAR_PLANILLA_SKU = 'CALIDAD_SOLICITAR_PLANILLA_SKU';
export const CALIDAD_GET_PLANILLA_OK = 'CALIDAD_GET_PLANILLA_OK';
export const CALIDAD_GUARDA_VALOR_IMAGEN = 'CALIDAD_GUARDA_VALOR_IMAGEN';
export const CALIDAD_ENVIA = 'CALIDAD_ENVIA';


export const CALIDAD_GUARDA_SEMANA = 'CALIDAD_GUARDA_SEMANA';
export const CALIDAD_GUARDA_DATA_SEMANA = 'CALIDAD_GUARDA_DATA_SEMANA';
export const CALIDAD_GUARDA_SALA = 'CALIDAD_GUARDA_SALA';
export const CALIDAD_GUARDA_CLIENTE = 'CALIDAD_GUARDA_CLIENTE';
export const CALIDAD_GUARDA_DATA_CLIENTE = 'CALIDAD_GUARDA_DATA_CLIENTE';
export const CALIDAD_GUARDA_SKU = 'CALIDAD_GUARDA_SKU';
export const CALIDAD_GUARDA_B_DETALLE = 'CALIDAD_GUARDA_B_DETALLE';
export const CALIDAD_GUARDA_ITEM = 'CALIDAD_GUARDA_ITEM';
export const CALIDAD_GUARDA_DESC_SKU = 'CALIDAD_GUARDA_DESC_SKU';

export const CALIDAD_GUARDA_DATA_EXH = 'CALIDAD_GUARDA_DATA_EXH';
export const CALIDAD_GUARDA_EXH = 'CALIDAD_GUARDA_EXH';
export const CALIDAD_GUARDA_DATA_PROMO = 'CALIDAD_GUARDA_DATA_PROMO';
export const CALIDAD_GUARDA_PROMO = 'CALIDAD_GUARDA_PROMO';
export const CALIDAD_GUARDA_FRENTES = 'CALIDAD_GUARDA_FRENTES';
export const CALIDAD_GUARDA_PRECIO = 'CALIDAD_GUARDA_PRECIO';
export const CALIDAD_NOMBRE_CLIENTE = 'CALIDAD_NOMBRE_CLIENTE';
export const CALIDAD_GUARDA_EXH_OLD = 'CALIDAD_GUARDA_EXH_OLD';
export const CALIDAD_GUARDA_PROMO_OLD = 'CALIDAD_GUARDA_PROMO_OLD';

export const CALIDAD_GUARDA_RESPUESTA_MOD = 'CALIDAD_GUARDA_RESPUESTA_MOD';

export const CALIDAD_ACTIVATION_ON = 'CALIDAD_ACTIVATION_ON';
export const CALIDAD_ACTIVATION_OFF = 'CALIDAD_ACTIVATION_OFF';

export const CALIDAD_VALIDAR_SKU = 'CALIDAD_VALIDAR_SKU';

export const CALIDAD_TIPO_MODIFICACION = 'CALIDAD_TIPO_MODIFICACION';
export const CALIDAD_GUARDA_PREDOMINANTE = 'CALIDAD_GUARDA_PREDOMINANTE';
export const CALIDAD_GUARDA_NRO_EXHIBIDOR = 'CALIDAD_GUARDA_NRO_EXHIBIDOR';
export const CALIDAD_GUARDA_NRO_EXHIBIDOR_OLD = 'CALIDAD_GUARDA_NRO_EXHIBIDOR_OLD';
export const CALIDAD_GUARDA_PREDOMINANTE_OLD = 'CALIDAD_GUARDA_PREDOMINANTE_OLD';