export const GUARDA_CLIENTE_PARAMETRO = 'GUARDA_CLIENTE_PARAMETRO';

export const CARGA_CLIENTE_PARAMETRO = 'CARGA_CLIENTE_PARAMETRO';
export const GUARDA_DATA_EXCEL_JSON = 'GUARDA_DATA_EXCEL_JSON';
export const GUARDA_DATA_ARRAY_EXCEL = 'GUARDA_DATA_ARRAY_EXCEL';
export const GUARDA_QUERY = 'GUARDA_QUERY';
export const GUARDA_JSON_BODY = 'GUARDA_JSON_BODY';

export const CARGA_INDICADOR_PARAMETRO = 'CARGA_INDICADOR_PARAMETRO';
export const GUARDA_INDICADOR_PARAMETRO = 'GUARDA_INDICADOR_PARAMETRO';