
export const CARGA_CLIENTE_PARAMETRO = 'CARGA_CLIENTE_PARAMETRO';
export const GUARDA_CLIENTE_PARAMETRO = 'GUARDA_CLIENTE_PARAMETRO';

export const CARGA_INDICADOR_PARAMETRO = 'CARGA_INDICADOR_PARAMETRO';
export const GUARDA_INDICADOR_PARAMETRO = 'GUARDA_INDICADOR_PARAMETRO';


