export const START_ACTION = 'START_ACTION';
export const STOP_ACTION = 'STOP_ACTION';

export const AGREGAR_NUMERO = 'AGREGAR_NUMERO';

export const CONTROL_CAMBIA_NUMERO = 'CONTROL_CAMBIA_NUMERO';
export const CONTROL_CAMBIA_NOMBRE = 'CONTROL_CAMBIA_NOMBRE';
export const CONTROL_CAMBIA_ESTADO = 'CONTROL_CAMBIA_ESTADO';

export const CONTROL_API_SEMANA = 'CONTROL_API_SEMANA';

export const CONTROL_GUARDO_PROFILE = 'CONTROL_GUARDO_PROFILE';
export const CONTROL_GUARDA_PUNTO = 'CONTROL_GUARDA_PUNTO';
export const CONTROL_GUARDA_DIA = 'CONTROL_GUARDA_DIA';
export const CONTROL_GUARDA_TAREA = 'CONTROL_GUARDA_TAREA';


export const CONTROL_GUARDA_NIVEL1 = 'CONTROL_GUARDA_NIVEL1';
export const CONTROL_GUARDA_NIVEL2 = 'CONTROL_GUARDA_NIVEL2';
export const CONTROL_GUARDA_NIVEL3 = 'CONTROL_GUARDA_NIVEL3';

export const CONTROL_BORRA_NIVEL1 = 'CONTROL_BORRA_NIVEL1';
export const CONTROL_BORRA_NIVEL2 = 'CONTROL_BORRA_NIVEL2';
export const CONTROL_BORRA_NIVEL3 = 'CONTROL_BORRA_NIVEL3';

export const CONTROL_BORRA_FETCH = 'CONTROL_BORRA_FETCH';