/* ATRIBUTOS OPERADOR*/

export const ECOM_GUARDA_ID_PROFILE = 'ECOM_GUARDA_ID_PROFILE';

/* ATRIBUTOS DE APOYO */

export const ECOM_GUARDA_PLATAFORMA = 'ECOM_GUARDA_PLATAFORMA';
export const ECOM_GUARDA_SALA = 'ECOM_GUARDA_SALA';
export const ECOM_GUARDA_DESC_SALA = 'ECOM_GUARDA_DESC_SALA';
export const ECOM_GUARDA_DESC_MARCA = 'ECOM_GUARDA_DESC_MARCA';
export const ECOM_GUARDA_DESC_SKU = 'ECOM_GUARDA_DESC_SKU';
export const ECOM_GUARDA_IMAGEN_SKU = 'ECOM_GUARDA_IMAGEN_SKU';


/* CAMPOS SOLICITADOS*/ 

export const ECOM_GUARDA_PRESENCIA = 'ECOM_GUARDA_PRESENCIA';
export const ECOM_GUARDA_STOCK = 'ECOM_GUARDA_STOCK';
export const ECOM_GUARDA_VALOR_IMAGEN = 'ECOM_GUARDA_VALOR_IMAGEN';
export const ECOM_GUARDA_DESCRIPCION_SKU = 'ECOM_GUARDA_DESCRIPCION_SKU';
export const ECOM_GUARDA_PRECIO_UNITARIO = 'ECOM_GUARDA_PRECIO_UNITARIO';
export const ECOM_GUARDA_PRECIO_DESCUENTO = 'ECOM_GUARDA_PRECIO_DESCUENTO';
export const ECOM_GUARDA_MECANICA = 'ECOM_GUARDA_MECANICA';
export const ECOM_GUARDA_ALERTA_QUIEBRE = 'ECOM_GUARDA_ALERTA_QUIEBRE';


export const ECOM_GET_SALA_OK = 'ECOM_GET_SALA_OK';
export const ECOM_GET_SALA_REQUEST = 'ECOM_GET_SALA_REQUEST';
export const ECOM_GET_SALA_ERROR = 'ECOM_GET_SALA_ERROR';

export const ECOM_GET_PLATAFORMA_OK = 'ECOM_GET_PLATAFORMA_OK';
export const ECOM_GET_PLANILLA_OK = 'ECOM_GET_PLANILLA_OK';

