export const GDS_START_ACTION = 'GDS_START_ACTION';
export const GDS_STOP_ACTION = 'GDS_STOP_ACTION';
export const GDS_AGREGAR_NUMERO = 'GDS_AGREGAR_NUMERO';
export const GDS_GUARDA_ESTADO = 'GDS_GUARDA_ESTADO';

export const GDS_GUARDA_SEMANA = 'GDS_GUARDA_SEMANA';
export const GDS_GUARDA_DATA_SEMANA = 'GDS_GUARDA_DATA_SEMANA';
export const GDS_GUARDA_DATA_CLIENTE_HTML = 'GDS_GUARDA_DATA_CLIENTE_HTML';
export const GDS_GUARDA_CLIENTE_HTML = 'GDS_GUARDA_CLIENTE_HTML';
export const GDS_GUARDA_SALA_HTML = 'GDS_GUARDA_SALA_HTML';
export const GDS_GUARDA_DATA_HTML = 'GDS_GUARDA_DATA_HTML';
export const GDS_BORRA_DATA_HTML = 'GDS_BORRA_DATA_HTML';
export const GDS_GUARDA_ESTADO_ALARMA = 'GDS_GUARDA_ESTADO_ALARMA';
export const GDS_GUARDA_B_DETALLE_AGRUPADA = 'GDS_GUARDA_B_DETALLE_AGRUPADA';
export const GDS_GUARDA_RESPUESTA_DELETE = 'GDS_GUARDA_RESPUESTA_DELETE';
export const GDS_GUARDA_B_DETALLE_EXH = 'GDS_GUARDA_B_DETALLE_EXH';
export const GDS_GUARDA_CLIENTE_DELETE = 'GDS_GUARDA_CLIENTE_DELETE';
export const GDS_GUARDA_CLIENTE_LOG = 'GDS_GUARDA_CLIENTE_LOG';
export const GDS_GUARDA_CLIENTE_ESQUEMA = 'GDS_GUARDA_CLIENTE_ESQUEMA';
export const GDS_GUARDA_CLIENTE_HTML_DELETE = 'GDS_GUARDA_CLIENTE_HTML_DELETE';
export const GDS_GUARDA_DATA_LOG = 'GDS_GUARDA_DATA_LOG';
export const GDS_BORRA_SEMANA = 'GDS_BORRA_SEMANA';

export const GDS_GUARDA_DATA_SEM_LOG = 'GDS_GUARDA_DATA_SEM_LOG';
export const GDS_GUARDA_SEM_LOG = 'GDS_GUARDA_SEM_LOG';

export const GDS_GUARDA_DATA_SERV_LOG = 'GDS_GUARDA_DATA_SERV_LOG';
export const GDS_GUARDA_SERV_LOG = 'GDS_GUARDA_SERV_LOG';

export const GDS_GUARDA_ESTADO_LOG = 'GDS_GUARDA_ESTADO_LOG';
export const GDS_GUARDA_ARRAY_LOG = 'GDS_GUARDA_ARRAY_LOG';

export const GDS_MESSAGE = 'GDS_MESSAGE';
export const GDS_GUARDA_ESTADO_OK = 'GDS_GUARDA_ESTADO_OK';
